/**
 * Canonical Founding 50 Town Register
 * 
 * This is the authoritative source of truth for the50 founding towns
 * seeded in the production-baseline migration (20260707002039).
 * 
 * Province assignments are canonical and enforced.
 * Display names are stored separately from normalised search forms.
 * 
 * DO NOT EDIT THIS FILE to add towns — new towns are added via database
 * migrations and must be reconciled here.
 */

export interface CanonicalTown {
  id: string;           // slug-based stable identifier
  name: string;         // official display name
  slug: string;         // URL-safe normalised form
  province: string;     // canonical province name
  provinceSlug: string; // province slug for routing
  aliases: string[];    // known alternative names/spellings
  isFounding: boolean;  // part of the Founding 50
}

export interface CanonicalProvince {
  name: string;
  slug: string;
  towns: CanonicalTown[];
}

// Founding 50 — extracted from 20260707002039_founding50_and_town_readiness.sql
const FOUNDING_TOWNS: CanonicalTown[] = [
  // Gauteng (8)
  { id: 'johannesburg', name: 'Johannesburg', slug: 'johannesburg', province: 'Gauteng', provinceSlug: 'gauteng', aliases: ['JOHANNESBURG'], isFounding: true },
  { id: 'pretoria', name: 'Pretoria', slug: 'pretoria', province: 'Gauteng', provinceSlug: 'gauteng', aliases: [], isFounding: true },
  { id: 'soweto', name: 'Soweto', slug: 'soweto', province: 'Gauteng', provinceSlug: 'gauteng', aliases: [], isFounding: true },
  { id: 'tembisa', name: 'Tembisa', slug: 'tembisa', province: 'Gauteng', provinceSlug: 'gauteng', aliases: [], isFounding: true },
  { id: 'springs', name: 'Springs', slug: 'springs', province: 'Gauteng', provinceSlug: 'gauteng', aliases: [], isFounding: true },
  { id: 'vanderbijlpark', name: 'Vanderbijlpark', slug: 'vanderbijlpark', province: 'Gauteng', provinceSlug: 'gauteng', aliases: [], isFounding: true },
  { id: 'randfontein', name: 'Randfontein', slug: 'randfontein', province: 'Gauteng', provinceSlug: 'gauteng', aliases: [], isFounding: true },
  { id: 'kempton-park', name: 'Kempton Park', slug: 'kempton-park', province: 'Gauteng', provinceSlug: 'gauteng', aliases: ['Kempton park'], isFounding: true },

  // Free State (8)
  { id: 'bloemfontein', name: 'Bloemfontein', slug: 'bloemfontein', province: 'Free State', provinceSlug: 'free-state', aliases: ['Bloemfontein Free State'], isFounding: true },
  { id: 'bethlehem', name: 'Bethlehem', slug: 'bethlehem', province: 'Free State', provinceSlug: 'free-state', aliases: [], isFounding: true },
  { id: 'harrismith', name: 'Harrismith', slug: 'harrismith', province: 'Free State', provinceSlug: 'free-state', aliases: [], isFounding: true },
  { id: 'ficksburg', name: 'Ficksburg', slug: 'ficksburg', province: 'Free State', provinceSlug: 'free-state', aliases: [], isFounding: true },
  { id: 'senekal', name: 'Senekal', slug: 'senekal', province: 'Free State', provinceSlug: 'free-state', aliases: [], isFounding: true },
  { id: 'ladybrand', name: 'Ladybrand', slug: 'ladybrand', province: 'Free State', provinceSlug: 'free-state', aliases: [], isFounding: true },
  { id: 'phuthaditjhaba', name: 'Phuthaditjhaba', slug: 'phuthaditjhaba', province: 'Free State', provinceSlug: 'free-state', aliases: [], isFounding: true },
  { id: 'welkom', name: 'Welkom', slug: 'welkom', province: 'Free State', provinceSlug: 'free-state', aliases: [], isFounding: true },

  // KwaZulu-Natal (7)
  { id: 'durban', name: 'Durban', slug: 'durban', province: 'KwaZulu-Natal', provinceSlug: 'kwaZulu-natal', aliases: [], isFounding: true },
  { id: 'newcastle', name: 'Newcastle', slug: 'newcastle', province: 'KwaZulu-Natal', provinceSlug: 'kwaZulu-natal', aliases: [], isFounding: true },
  { id: 'kokstad', name: 'Kokstad', slug: 'kokstad', province: 'KwaZulu-Natal', provinceSlug: 'kwaZulu-natal', aliases: [], isFounding: true },
  { id: 'harding', name: 'Harding', slug: 'harding', province: 'KwaZulu-Natal', provinceSlug: 'kwaZulu-natal', aliases: [], isFounding: true },
  { id: 'greytown', name: 'Greytown', slug: 'greytown', province: 'KwaZulu-Natal', provinceSlug: 'kwaZulu-natal', aliases: [], isFounding: true },
  { id: 'nquthu', name: 'Nquthu', slug: 'nquthu', province: 'KwaZulu-Natal', provinceSlug: 'kwaZulu-natal', aliases: [], isFounding: true },
  { id: 'richards-bay', name: 'Richards Bay', slug: 'richards-bay', province: 'KwaZulu-Natal', provinceSlug: 'kwaZulu-natal', aliases: [], isFounding: true },

  // Eastern Cape (5)
  { id: 'matatiele', name: 'Matatiele', slug: 'matatiele', province: 'Eastern Cape', provinceSlug: 'eastern-cape', aliases: [], isFounding: true },
  { id: 'kwamaqoma', name: 'KwaMaqoma', slug: 'kwamaqoma', province: 'Eastern Cape', provinceSlug: 'eastern-cape', aliases: [], isFounding: true },
  { id: 'mthatha', name: 'Mthatha', slug: 'mthatha', province: 'Eastern Cape', provinceSlug: 'eastern-cape', aliases: [], isFounding: true },
  { id: 'gqeberha', name: 'Gqeberha', slug: 'gqeberha', province: 'Eastern Cape', provinceSlug: 'eastern-cape', aliases: [], isFounding: true },
  { id: 'east-london', name: 'East London', slug: 'east-london', province: 'Eastern Cape', provinceSlug: 'eastern-cape', aliases: [], isFounding: true },

  // Mpumalanga (5)
  { id: 'emalahleni', name: 'Emalahleni', slug: 'emalahleni', province: 'Mpumalanga', provinceSlug: 'mpumalanga', aliases: [], isFounding: true },
  { id: 'bushbuckridge', name: 'Bushbuckridge', slug: 'bushbuckridge', province: 'Mpumalanga', provinceSlug: 'mpumalanga', aliases: ['Bushbukridge'], isFounding: true },
  { id: 'acornhoek', name: 'Acornhoek', slug: 'acornhoek', province: 'Mpumalanga', provinceSlug: 'mpumalanga', aliases: [], isFounding: true },
  { id: 'sabie', name: 'Sabie', slug: 'sabie', province: 'Mpumalanga', provinceSlug: 'mpumalanga', aliases: ['Sabbie', 'Hazyview'], isFounding: true },
  { id: 'mbombela', name: 'Mbombela', slug: 'mbombela', province: 'Mpumalanga', provinceSlug: 'mpumalanga', aliases: [], isFounding: true },

  // Limpopo (5)
  { id: 'burgersfort', name: 'Burgersfort', slug: 'burgersfort', province: 'Limpopo', provinceSlug: 'limpopo', aliases: ['Burgersford'], isFounding: true },
  { id: 'mokopane', name: 'Mokopane', slug: 'mokopane', province: 'Limpopo', provinceSlug: 'limpopo', aliases: [], isFounding: true },
  { id: 'polokwane', name: 'Polokwane', slug: 'polokwane', province: 'Limpopo', provinceSlug: 'limpopo', aliases: [], isFounding: true },
  { id: 'tzaneen', name: 'Tzaneen', slug: 'tzaneen', province: 'Limpopo', provinceSlug: 'limpopo', aliases: [], isFounding: true },
  { id: 'thohoyandou', name: 'Thohoyandou', slug: 'thohoyandou', province: 'Limpopo', provinceSlug: 'limpopo', aliases: [], isFounding: true },

  // North West (4)
  { id: 'brits', name: 'Brits', slug: 'brits', province: 'North West', provinceSlug: 'north-west', aliases: [], isFounding: true },
  { id: 'rustenburg', name: 'Rustenburg', slug: 'rustenburg', province: 'North West', provinceSlug: 'north-west', aliases: [], isFounding: true },
  { id: 'mahikeng', name: 'Mahikeng', slug: 'mahikeng', province: 'North West', provinceSlug: 'north-west', aliases: [], isFounding: true },
  { id: 'klerksdorp', name: 'Klerksdorp', slug: 'klerksdorp', province: 'North West', provinceSlug: 'north-west', aliases: [], isFounding: true },

  // Western Cape (4)
  { id: 'cape-town', name: 'Cape Town', slug: 'cape-town', province: 'Western Cape', provinceSlug: 'western-cape', aliases: [], isFounding: true },
  { id: 'george', name: 'George', slug: 'george', province: 'Western Cape', provinceSlug: 'western-cape', aliases: [], isFounding: true },
  { id: 'paarl', name: 'Paarl', slug: 'paarl', province: 'Western Cape', provinceSlug: 'western-cape', aliases: [], isFounding: true },
  { id: 'worcester', name: 'Worcester', slug: 'worcester', province: 'Western Cape', provinceSlug: 'western-cape', aliases: [], isFounding: true },

  // Northern Cape (4)
  { id: 'kimberley', name: 'Kimberley', slug: 'kimberley', province: 'Northern Cape', provinceSlug: 'northern-cape', aliases: [], isFounding: true },
  { id: 'upington', name: 'Upington', slug: 'upington', province: 'Northern Cape', provinceSlug: 'northern-cape', aliases: [], isFounding: true },
  { id: 'kuruman', name: 'Kuruman', slug: 'kuruman', province: 'Northern Cape', provinceSlug: 'northern-cape', aliases: [], isFounding: true },
  { id: 'de-aar', name: 'De Aar', slug: 'de-aar', province: 'Northern Cape', provinceSlug: 'northern-cape', aliases: [], isFounding: true },
];

// Build province index
const PROVINCES: CanonicalProvince[] = [];
const provinceMap = new Map<string, CanonicalProvince>();

for (const town of FOUNDING_TOWNS) {
  let province = provinceMap.get(town.province);
  if (!province) {
    province = { name: town.province, slug: town.provinceSlug, towns: [] };
    provinceMap.set(town.province, province);
    PROVINCES.push(province);
  }
  province.towns.push(town);
}

// Lookup indices
const TOWN_BY_SLUG = new Map<string, CanonicalTown>();
const TOWN_BY_ID = new Map<string, CanonicalTown>();
const TOWN_BY_ALIAS = new Map<string, CanonicalTown>();

for (const town of FOUNDING_TOWNS) {
  TOWN_BY_SLUG.set(town.slug, town);
  TOWN_BY_ID.set(town.id, town);
  for (const alias of town.aliases) {
    TOWN_BY_ALIAS.set(alias.toLowerCase(), town);
  }
}

// ============================================================
// PUBLIC API
// ============================================================

/** All9 provinces with their founding towns */
export const CANONICAL_PROVINCES: readonly CanonicalProvince[] = PROVINCES;

/** All50 founding towns */
export const CANONICAL_TOWNS: readonly CanonicalTown[] = FOUNDING_TOWNS;

/** Total founding town count */
export const FOUNDING_TOWN_COUNT = FOUNDING_TOWNS.length;

/** Look up a town by slug (primary key) */
export function getTownBySlug(slug: string): CanonicalTown | undefined {
  return TOWN_BY_SLUG.get(slug);
}

/** Look up a town by id (same as slug for canonical towns) */
export function getTownById(id: string): CanonicalTown | undefined {
  return TOWN_BY_ID.get(id);
}

/** Look up a town by alias (case-insensitive) */
export function getTownByAlias(alias: string): CanonicalTown | undefined {
  return TOWN_BY_ALIAS.get(alias.toLowerCase());
}

/** Resolve a town from any known identifier (slug, id, or alias) */
export function resolveTown(identifier: string): CanonicalTown | undefined {
  return getTownBySlug(identifier) 
    ?? getTownById(identifier) 
    ?? getTownByAlias(identifier);
}

/** Get province for a town slug */
export function getProvinceForTown(townSlug: string): CanonicalProvince | undefined {
  const town = getTownBySlug(townSlug);
  if (!town) return undefined;
  return provinceMap.get(town.province);
}

/** Get all towns in a province */
export function getTownsInProvince(provinceSlug: string): CanonicalTown[] {
  const province = PROVINCES.find(p => p.slug === provinceSlug);
  return province?.towns ?? [];
}

/** Search towns by name (fuzzy match) */
export function searchTowns(query: string): CanonicalTown[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  
  return FOUNDING_TOWNS.filter(t => 
    t.name.toLowerCase().includes(q) || 
    t.slug.includes(q) ||
    t.aliases.some(a => a.toLowerCase().includes(q))
  );
}

/** Validate that a town slug is in the canonical register */
export function isCanonicalTown(slug: string): boolean {
  return TOWN_BY_SLUG.has(slug);
}

/** Validate that a province slug is canonical */
export function isCanonicalProvince(provinceSlug: string): boolean {
  return provinceMap.has(provinceSlug) || PROVINCES.some(p => p.slug === provinceSlug);
}
