import type { ReactNode } from 'react';
import Link from 'next/link';
import type { Resource } from '@/lib/living-town/contracts';
export function EmptyState({ children = 'Nothing is visible here yet.' }: { children?: ReactNode }) { return <div className="lt-state"><p>{children}</p></div>; }
export function LoadingState() { return <div className="lt-state" data-tone="loading" role="status">Loading your next move…</div>; }
export function ErrorState({ children = 'We could not load this. Please try again.' }: { children?: ReactNode }) { return <div className="lt-state" data-tone="error" role="alert"><p>{children}</p><a className="lt-help" href="">Try again</a></div>; }
export function PermissionState({ children = 'Your account cannot view this yet.' }: { children?: ReactNode }) { return <div className="lt-state"><p>{children}</p><a className="lt-help" href="#kopano">Get help</a></div>; }
export function OfflineState() { return <div className="lt-state" data-tone="offline" role="status">You’re offline. Information may be out of date. Reconnect before continuing; nothing is queued or submitted.</div>; }
export function ResourceView<T>({ value, children, empty }: { value: Resource<T[]>; children: (data: T[]) => ReactNode; empty: string }) {
  if (value.state === 'error') return <ErrorState>{value.message}</ErrorState>;
  if (value.state !== 'ready') return <PermissionState>{value.message}</PermissionState>;
  return value.data.length ? <>{children(value.data)}</> : <EmptyState>{empty}</EmptyState>;
}
export function NextActionCard({ title, reason, href, kind }: { title: string; reason: string; href: string; kind: string }) { return <article className="lt-card lt-next"><p className="lt-eyebrow">Your next move</p><h2>{title}</h2><p>{reason}</p><p>{kind.replaceAll('_', ' ')}</p><Link prefetch={false} className="lt-button" href={href}>View next move <span aria-hidden="true">→</span></Link></article>; }
export function TownPulse({ count }: { count: Resource<number> }) { return <div className="lt-card">{count.state === 'ready' ? <><span className="lt-stat">{count.data}</span><p>work records visible in this town</p><p className="lt-subtle">Recorded work, across all dates. This is not a count of active Builders or verified proof.</p></> : count.state === 'error' ? <ErrorState>{count.message}</ErrorState> : <PermissionState>{count.message}</PermissionState>}</div>; }
export function TownSignal({ title, category }: { title: string; category?: string | null }) { return <article className="lt-card lt-signal"><p className="lt-subtle">{category || 'Town signal'}</p><h3>{title}</h3></article>; }
export function MissionCard({ title, href, description }: { title: string; href: string; description?: string | null }) { return <article className="lt-card"><h3>{title}</h3>{description && <p className="lt-subtle">{description}</p>}<Link prefetch={false} className="lt-help" href={href}>View mission →</Link></article>; }
export function OpportunityCard({ title, description, href }: { title: string; description: string; href?: string }) { return <article className="lt-card"><h3>{title}</h3><p>{description}</p>{href ? <Link className="lt-help" href={href}>View opportunity</Link> : <span className="lt-pill">Not available yet</span>}</article>; }
export function PeopleChip({ name }: { name: string }) { return <span className="lt-person"><span className="lt-avatar" aria-hidden="true">{name.trim().slice(0, 1)}</span>{name}</span>; }
export function BuilderCard({ name, children }: { name: string; children?: ReactNode }) { return <article className="lt-card"><PeopleChip name={name} />{children}</article>; }
export function CapabilityIndicator({ name, verified = false }: { name: string; verified?: boolean }) { return <span className={verified ? 'lt-pill lt-success' : 'lt-pill'}>{name} · {verified ? 'Verified' : 'Requirements not verified'}</span>; }
export function ProgressIndicator({ completed, required }: { completed: number; required: number }) { return required > 0 ? <div><progress value={Math.max(0, Math.min(completed, required))} max={required} aria-label="Verified requirements" /><p className="lt-subtle">{Math.max(0, Math.min(completed, required))} of {required} requirements verified</p></div> : <EmptyState>Requirements have not been defined yet.</EmptyState>; }
export function ProofStatus({ status }: { status: string }) { const labels: Record<string, string> = { pending: 'Awaiting review', approved: 'Recorded as approved', returned: 'Returned for changes', rejected: 'Not approved' }; return <span className="lt-pill">{labels[status] || 'Review status unavailable'}</span>; }
export function ActivityItem({ title, status, href }: { title: string; status: string; href: string }) { const labels: Record<string, string> = { draft: 'Draft', submitted: 'Submitted', in_review: 'In review', published: 'Published', rejected: 'Returned', approved: 'Approved' }; return <article><h3>{title}</h3><span className="lt-pill">{labels[status] || 'Status unavailable'}</span> <Link prefetch={false} className="lt-help" href={href}>View work</Link></article>; }
export function LearningBite({ title, children }: { title: string; children: ReactNode }) { return <article className="lt-card"><h3>{title}</h3>{children}</article>; }
export function KopanoPrompt() { return <section id="kopano" className="lt-card lt-kopano"><p className="lt-eyebrow">Kopano · here to help</p><h2>One step at a time.</h2><details><summary>What should I do next?</summary><p>Start with Your next move. Read the mission or existing work before deciding what to do.</p></details><details><summary>What makes useful proof?</summary><p>Explain what happened, where and when. Ask permission before photographing people. Submission is not verification: an authorised reviewer must check the evidence.</p></details><details><summary>My town or access is missing</summary><p>Ask your town steward or Head of People to check your town assignment. You do not need to create another account.</p></details></section>; }
